### PR TITLE
Add new article

### PR DESCRIPTION
**Pull request by AkashKrDutta**

### CODE REVIEW

**Comment by sakshamsharma** [comment]
Hi, I guess you can see the build fails because of file encoding. Please write the file in Linux (I believe it should solve the issue).
Also, headings don't need this format:

```
###**abc**
```

Instead, they are simply:

```
### HEADING
```

Please fix these issues. Thanks!

**Comment by sakshamsharma** [comment]
The headings are still not fixed :stuck_out_tongue:
Also, the double quotes were the issue, you're right (I remember running into this issue earlier sometime as well). That's windows. But I still don't know why the new characters don't display on GitHub when you look at the `Files Changed` tab above.

**Comment by AkashKrDutta** [comment]
yeah , i missed it completely :stuck_out_tongue:

**Comment by sakshamsharma** [comment]
Hey! Mostly it's resolved. But please use triple backticks (the one to the left of the digit '1' on keyboard).
Please remove the `>` symbols on each line. Instead, use this syntax:

```
(triple back ticks) (please, don't write the text, actually type the backticks)
code
code
more code
(triple back ticks)
```

**Comment by AkashKrDutta** [comment]
done i guess

**Comment by sakshamsharma** [comment]
Looks fine as of now. Pretty sure there'd be some changes needed :p Cannot compile rn to test.

**Pull request merged**
