### PR TITLE
Article on Dynamic Progamming Optimization using Convex Hull Trick

### PR DESCRIPTION
**Pull request by GinugaSaketh**

### CODE REVIEW

**Comment by sakshamsharma** [comment]
Hi!
Thanks for the article. Could you add a category called "Algos" ? The category is empty right now. Also add a tag called competitive. (Mind the capitalizations)

Finally, can you also update the date so the article comes at the top of our website?

**Comment by GinugaSaketh** [comment]
ok, I made the changes.

**Comment by sakshamsharma** [comment]
There is an extra space after `category:`, remove that please.

**Comment by GinugaSaketh** [comment]
k done

**Comment by sakshamsharma** [comment]
Merged. Thanks.

**Pull request merged**
