### PR TITLE
Summer Project 2016 Machine Learning

### PR DESCRIPTION
**Pull request by adjhawar**
The project is on Forex prediction and has been done by the group "Code Assassins"

### CODE REVIEW

**Comment by sakshamsharma** [comment]
Can you please change headings to follow this syntax:

```
### Sub heading
```

(note the space before the alphabets)

Also, please add newlines where needed. For instance, before the subheading, there should be atleast one blank line. This is to ensure compatibility.
Thanks.

**Comment by sakshamsharma** [comment]
Also, it would be nice if you describe your project a bit more. For instance, what you learned and how it is working. Another para would be enough and nice :smile:

**Comment by adjhawar** [comment]
I have incorporated the changes and sent a new pull request...:)

**Comment by sakshamsharma** [comment]
Cool! This will be merged in due time (got to keep a moderate flow of articles).
Thanks!

**Comment by sakshamsharma** [comment]
Sorry for the late merge. There are a couple of mistakes in the file format. I'll handle them, and link you to the commit where I fix them, for your knowledge sake :smile:

**Comment by sakshamsharma** [comment]
Here are the changes:
https://github.com/pclubiitk/pclub.in/commit/51fe2733ca49224924815fd8dee51853e467cad5

**Comment by adjhawar** [comment]
thanks...:)

**Pull request merged**
