### PR TITLE
Added post on installing plugins in vim

### PR DESCRIPTION
**Pull request by yashsriv**
Please review and suggest changes if any before merging

### CODE REVIEW

**Comment by sakshamsharma** [comment]
Its actually quite verbose. Would scare off people. Since you can never hold someone's finger when they walk into the ocean (read: complex things), I recommend you delete the section on Dein and just keep a single line about it. And you should really make the section on vim-plug as the top one. Remember that the target audience is not a super experienced group of people, so we need simple language and we should not talk about a lot of crap.
To that end, remove the useless information about vundle, pathogen etc. They're easy enough to install, their README is explantory. Just tell them how to install vim-plug, and write 2 lines each about other plugin managers. That way, they will not be confused when they read the word "pathogen" online somewhere, but they will also not be intimidated on seeing such a large article.

**Comment by yashsriv** [comment]
I have updated the sections to just reflect advantages and disadvantages

**Comment by sakshamsharma** [comment]
The vim-plug section is too long and scary. Please trim it down to a basic section, and move the advanced usage, the 'do' section et cetera to the end of the document. Also, change the post title to something like "Plugin Management in Vim".

**Comment by yashsriv** [comment]
Simplified it

**Pull request merged**
