### PR TITLE
Added Coordinators 2022-23

### PR DESCRIPTION
**Pull request by 7shivamx**

### CODE REVIEW

**Review by adarshaj — CHANGES_REQUESTED** [review]
There are unnecessary changes. Please fix the following:

- [ ] Undo canonical url change from `https://pclub.in` to `http://0.0.0.0:8080`. 
- [ ] Undo date changes in posts which were already published.

**Comment by 7shivamx** [comment]
> There are unnecessary changes. Please fix the following:
> 
> * [ ]  Undo canonical url change from `https://pclub.in` to `http://0.0.0.0:8080`.
> * [ ]  Undo date changes in posts which were already published.

Made the requested changes. Kindly have a look at the changes and let me know if anything needs to be changed

**Review by adarshaj — DISMISSED** [review]
@7shivamx - sorry! I didn't get notified of changes.

LGTM 👍

**Comment by adarshaj** [comment]
Oh wait, you made changes to gh-pages branch? I don't think we need to touch there, we just modify the master branch. It will get built and deployed? I'm not aware of latest process to deploy... 

May be one of recent ex-co-ordinators need to cross check. /cc @namangup @SomTambe  @dryairship 

For reference, here are previous PR on adding new co-ordinators.. #120 #106

**Comment by SomTambe** [comment]
@adarshaj yeah afaik changes have to be done on `master` branch, `gh-pages` gets automatically generated by github pages while building and deploying. you don't have to touch the `gh-pages` branch.

**Comment by namangup** [comment]
@adarshaj @SomTambe We are using travis as CI/CD which has recently migrated from travis-ci.org to .com breaking old CI integrations. That apparently needs some org owner rights which I don't have, I'm planning to get GitHub actions added instead.

**Comment by adarshaj** [comment]
@namangup - made you the org owner, since you are the coordinator. now you should have all the privileges there is.

**Pull request closed without merging**
