### PR TITLE
Add post on valid Open Source contributions

### PR DESCRIPTION
**Pull request by milindl**
I'm unsure whether the title is the best. But seems OK.

### CODE REVIEW

**Comment by yashsriv** [comment]
Could you please amend the commit message:

> Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
> or "Fixes bug."  This convention matches up with commit messages generated
> by commands like git merge and git revert.
- From [Good Commit Messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

**Comment by yashsriv** [comment]
Also I get 404 for https://github.com/AP-whitehat

**Comment by milindl** [comment]
@yashsriv Fixed.

On another note, see https://secure.phabricator.com/book/phabflavor/article/writing_reviewable_code (the last part of the Commit Messages section). Interesting. 80 character limit < better message. But this discussion can take place later.

**Comment by yashsriv** [comment]
@milindl AP-whitehat url still not fixed

**Comment by sakshamsharma** [comment]
Also add image of the tshirts :smile:

**Comment by milindl** [comment]
@yashsriv thanks for the review, I'd only fixed the name!
@sakshamsharma okay

**Comment by pallavagarwal07** [comment]
Everything seems fine. Merging

**Comment by milindl** [comment]
Two things: 
* The "preview" of the post (on the homepage) is incorrect; anyway to fix that? 
* GitHub markdown turns https://li.nk to links automatically, but the site does not, this is an easy fix

**Comment by yashsriv** [comment]
* Jekyll offers a feature to specify the excerpt separator: [Link](https://jekyllrb.com/docs/posts/#post-excerpts).
* For the links just surrounding with box brackets [should be enough](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)

P.S. You should have built the site and tested it.
P.P.S. We should have also done that 😝

**Pull request merged**
